def compute(num1, num2):
    try:
        return num1 + num2
    except:
        raise Exception('Error') 
